/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_filereader.check" instead.
 */

#include <check.h>

#line 1 "test_filereader.check"
#include <check.h>

#include "athenianTransform.h"
#include "fileReader.h"

START_TEST(test_1) {
#line 6
    matrix_t *vert = NULL;
    matrix_t *vertNorm = NULL;
    matrix_t *vertTex = NULL;
    surface_t *surfaces = NULL;
    count_v counts = {0, 0, 0, 0};
    readFile(&vert, &vertNorm, &vertTex, &surfaces, "objects/test.obj", &counts);
    matrix_t vert_expected[8];
    for (int i = 0; i < 8; i++) vert_expected[i] = s21_create_matrix(4, 1);
    matrix_t vertTex_expected[14];
    for (int i = 0; i < 14; i++) vertTex_expected[i] = s21_create_matrix(2, 1);
    matrix_t vertNorm_expected[6];
    for (int i = 0; i < 6; i++) vertNorm_expected[i] = s21_create_matrix(4, 1);

    surface_t surfaces_expected[12];
    for (int i = 0; i < 12; i++) {
        surfaces_expected[i].ver_t = calloc(3, sizeof(int));
    }
    vert_expected[0].matrix[0][0] = 1.000000;
    vert_expected[0].matrix[1][0] = -1.000000;
    vert_expected[0].matrix[2][0] = -1.000000;
    vert_expected[0].matrix[3][0] = 1.000000;
    vert_expected[1].matrix[0][0] = 1.000000;
    vert_expected[1].matrix[1][0] = -1.000000;
    vert_expected[1].matrix[2][0] = 1.000000;
    vert_expected[1].matrix[3][0] = 1.000000;
    vert_expected[2].matrix[0][0] = -1.000000;
    vert_expected[2].matrix[1][0] = -1.000000;
    vert_expected[2].matrix[2][0] = 1.000000;
    vert_expected[2].matrix[3][0] = 1.000000;
    vert_expected[3].matrix[0][0] = -1.000000;
    vert_expected[3].matrix[1][0] = -1.000000;
    vert_expected[3].matrix[2][0] = -1.000000;
    vert_expected[3].matrix[3][0] = 1.000000;
    vert_expected[4].matrix[0][0] = 1.000000;
    vert_expected[4].matrix[1][0] = 1.000000;
    vert_expected[4].matrix[2][0] = -0.999999;
    vert_expected[4].matrix[3][0] = 1.000000;
    vert_expected[5].matrix[0][0] = 0.999999;
    vert_expected[5].matrix[1][0] = 1.000000;
    vert_expected[5].matrix[2][0] = 1.000001;
    vert_expected[5].matrix[3][0] = 1.000000;
    vert_expected[6].matrix[0][0] = -1.000000;
    vert_expected[6].matrix[1][0] = 1.000000;
    vert_expected[6].matrix[2][0] = 1.000000;
    vert_expected[6].matrix[3][0] = 1.000000;
    vert_expected[7].matrix[0][0] = -1.000000;
    vert_expected[7].matrix[1][0] = 1.000000;
    vert_expected[7].matrix[2][0] = -1.000000;
    vert_expected[7].matrix[3][0] = 1.000000;
    vertTex_expected[0].matrix[0][0] = 1.000000;
    vertTex_expected[0].matrix[1][0] = 0.333333;
    vertTex_expected[1].matrix[0][0] = 1.000000;
    vertTex_expected[1].matrix[1][0] = 0.666667;
    vertTex_expected[2].matrix[0][0] = 0.666667;
    vertTex_expected[2].matrix[1][0] = 0.666667;
    vertTex_expected[3].matrix[0][0] = 0.666667;
    vertTex_expected[3].matrix[1][0] = 0.333333;
    vertTex_expected[4].matrix[0][0] = 0.666667;
    vertTex_expected[4].matrix[1][0] = 0.000000;
    vertTex_expected[5].matrix[0][0] = 0.000000;
    vertTex_expected[5].matrix[1][0] = 0.333333;
    vertTex_expected[6].matrix[0][0] = 0.000000;
    vertTex_expected[6].matrix[1][0] = 0.000000;
    vertTex_expected[7].matrix[0][0] = 0.333333;
    vertTex_expected[7].matrix[1][0] = 0.000000;
    vertTex_expected[8].matrix[0][0] = 0.333333;
    vertTex_expected[8].matrix[1][0] = 1.000000;
    vertTex_expected[9].matrix[0][0] = 0.000000;
    vertTex_expected[9].matrix[1][0] = 1.000000;
    vertTex_expected[10].matrix[0][0] = 0.000000;
    vertTex_expected[10].matrix[1][0] = 0.666667;
    vertTex_expected[11].matrix[0][0] = 0.333333;
    vertTex_expected[11].matrix[1][0] = 0.333333;
    vertTex_expected[12].matrix[0][0] = 0.333333;
    vertTex_expected[12].matrix[1][0] = 0.666667;
    vertTex_expected[13].matrix[0][0] = 1.000000;
    vertTex_expected[13].matrix[1][0] = 0.000000;
    vertNorm_expected[0].matrix[0][0] = 0.000000;
    vertNorm_expected[0].matrix[1][0] = -1.000000;
    vertNorm_expected[0].matrix[2][0] = 0.000000;
    vertNorm_expected[0].matrix[3][0] = 1.000000;
    vertNorm_expected[1].matrix[0][0] = 0.000000;
    vertNorm_expected[1].matrix[1][0] = 1.000000;
    vertNorm_expected[1].matrix[2][0] = 0.000000;
    vertNorm_expected[1].matrix[3][0] = 1.000000;
    vertNorm_expected[2].matrix[0][0] = 1.000000;
    vertNorm_expected[2].matrix[1][0] = 0.000000;
    vertNorm_expected[2].matrix[2][0] = 0.000000;
    vertNorm_expected[2].matrix[3][0] = 1.000000;
    vertNorm_expected[3].matrix[0][0] = -0.000000;
    vertNorm_expected[3].matrix[1][0] = 0.000000;
    vertNorm_expected[3].matrix[2][0] = 1.000000;
    vertNorm_expected[3].matrix[3][0] = 1.000000;
    vertNorm_expected[4].matrix[0][0] = -1.000000;
    vertNorm_expected[4].matrix[1][0] = -0.000000;
    vertNorm_expected[4].matrix[2][0] = -0.000000;
    vertNorm_expected[4].matrix[3][0] = 1.000000;
    vertNorm_expected[5].matrix[0][0] = 0.000000;
    vertNorm_expected[5].matrix[1][0] = 0.000000;
    vertNorm_expected[5].matrix[2][0] = -1.000000;
    vertNorm_expected[5].matrix[3][0] = 1.000000;

    surfaces_expected[0].ver_t[0] = 2;
    surfaces_expected[0].ver_t[1] = 3;
    surfaces_expected[0].ver_t[2] = 4;
    surfaces_expected[1].ver_t[0] = 8;
    surfaces_expected[1].ver_t[1] = 7;
    surfaces_expected[1].ver_t[2] = 6;
    surfaces_expected[2].ver_t[0] = 5;
    surfaces_expected[2].ver_t[1] = 6;
    surfaces_expected[2].ver_t[2] = 2;
    surfaces_expected[3].ver_t[0] = 6;
    surfaces_expected[3].ver_t[1] = 7;
    surfaces_expected[3].ver_t[2] = 3;
    surfaces_expected[4].ver_t[0] = 3;
    surfaces_expected[4].ver_t[1] = 7;
    surfaces_expected[4].ver_t[2] = 8;
    surfaces_expected[5].ver_t[0] = 1;
    surfaces_expected[5].ver_t[1] = 4;
    surfaces_expected[5].ver_t[2] = 8;
    surfaces_expected[6].ver_t[0] = 1;
    surfaces_expected[6].ver_t[1] = 2;
    surfaces_expected[6].ver_t[2] = 4;
    surfaces_expected[7].ver_t[0] = 5;
    surfaces_expected[7].ver_t[1] = 8;
    surfaces_expected[7].ver_t[2] = 6;
    surfaces_expected[8].ver_t[0] = 1;
    surfaces_expected[8].ver_t[1] = 5;
    surfaces_expected[8].ver_t[2] = 2;
    surfaces_expected[9].ver_t[0] = 2;
    surfaces_expected[9].ver_t[1] = 6;
    surfaces_expected[9].ver_t[2] = 3;
    surfaces_expected[10].ver_t[0] = 4;
    surfaces_expected[10].ver_t[1] = 3;
    surfaces_expected[10].ver_t[2] = 8;
    surfaces_expected[11].ver_t[0] = 5;
    surfaces_expected[11].ver_t[1] = 1;
    surfaces_expected[11].ver_t[2] = 8;

    for (int i = 0; i < 8; i++) {
        int matr_res = s21_eq_matrix(&vert[i], &vert_expected[i]);
        ck_assert_int_eq(matr_res, 1);
    }

    for (int i = 0; i < 14; i++) {
        char str1[100], str2[100], str3[100], str4[100];
        snprintf(str1, sizeof(char) * 100, "%.6Lf", vertTex[i].matrix[0][0]);
        snprintf(str2, sizeof(char) * 100, "%.6Lf", vertTex_expected[i].matrix[0][0]);
        snprintf(str3, sizeof(char) * 100, "%.6Lf", vertTex[i].matrix[0][1]);
        snprintf(str4, sizeof(char) * 100, "%.6Lf", vertTex_expected[i].matrix[0][1]);
        ck_assert_str_eq(str1, str2);
        ck_assert_str_eq(str3, str4);
    }

    for (int i = 0; i < 6; i++) {
        int matr_res = s21_eq_matrix(&vertNorm[i], &vertNorm_expected[i]);
        ck_assert_int_eq(matr_res, 1);
    }
    for (int i = 0; i < 12; i++) {
        ck_assert_int_eq(surfaces[i].ver_t[0], surfaces_expected[i].ver_t[0]);
        ck_assert_int_eq(surfaces[i].ver_t[1], surfaces_expected[i].ver_t[1]);
        ck_assert_int_eq(surfaces[i].ver_t[2], surfaces_expected[i].ver_t[2]);
    }

    freeVerticesMatrix(&vert, &vertNorm, &vertTex, &surfaces, 8, 6, 14, 12);
    for (int i = 0; i < 8; i++) s21_remove_matrix(&vert_expected[i]);
    for (int i = 0; i < 14; i++) s21_remove_matrix(&vertTex_expected[i]);
    for (int i = 0; i < 6; i++) s21_remove_matrix(&vertNorm_expected[i]);
    for (int i = 0; i < 12; i++) {
        free(surfaces_expected[i].ver_t);
    }
}
END_TEST

START_TEST(test_2) {
#line 186
    matrix_t point = s21_create_matrix(4, 1);
    point.matrix[0][0] = 1.0;
    point.matrix[1][0] = 1.0;
    point.matrix[2][0] = 1.0;
    point.matrix[3][0] = 1.0;

    move_model(&point, 1, 1, 1, 1);
    matrix_t expected_point = s21_create_matrix(4, 1);
    expected_point.matrix[0][0] = 2.0;
    expected_point.matrix[1][0] = 2.0;
    expected_point.matrix[2][0] = 2.0;
    expected_point.matrix[3][0] = 1.0;

    int matr_res = s21_eq_matrix(&point, &expected_point);
    ck_assert_int_eq(matr_res, 1);
}
END_TEST

START_TEST(test_3) {
#line 203
    matrix_t point = s21_create_matrix(4, 1);
    point.matrix[0][0] = 1.0;
    point.matrix[1][0] = 1.0;
    point.matrix[2][0] = 1.0;
    point.matrix[3][0] = 1.0;

    resize_model(&point, 2, 2, 2, 1);
    matrix_t expected_point = s21_create_matrix(4, 1);
    expected_point.matrix[0][0] = 2.0;
    expected_point.matrix[1][0] = 2.0;
    expected_point.matrix[2][0] = 1.0;
    expected_point.matrix[3][0] = 1.0;

    int matr_res = s21_eq_matrix(&point, &expected_point);
    ck_assert_int_eq(matr_res, 1);
}
END_TEST

START_TEST(test_4) {
#line 220
    matrix_t point = s21_create_matrix(4, 1);
    point.matrix[0][0] = 1.0;
    point.matrix[1][0] = 1.0;
    point.matrix[2][0] = 1.0;
    point.matrix[3][0] = 1.0;

    rotate_model(&point, 1, 1, 1, 1);
    matrix_t expected_point = s21_create_matrix(4, 1);
    expected_point.matrix[0][0] = 0.999693;
    expected_point.matrix[1][0] = 1.000005;
    expected_point.matrix[2][0] = 1.000302;
    expected_point.matrix[3][0] = 1.0;

    int matr_res = s21_eq_matrix(&point, &expected_point);
    ck_assert_int_eq(matr_res, 1);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_1);
    tcase_add_test(tc1_1, test_2);
    tcase_add_test(tc1_1, test_3);
    tcase_add_test(tc1_1, test_4);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
